# An example architecture. Runs a server on port 80 corresponding
# to the endpoints you should implement.
version: '3'
services:
  app:
    # this is a simple flask webserver
    build: ./app
    ports:
      - 80:80
    environment:
        MONGO_USERNAME: root
        MONGO_PASSWORD: example
    links:
        - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - "27017:27017"
  adapter:
    # the service that scrapes the website and endpoints
    build: ./adapter
    environment:
        MONGO_USERNAME: root
        MONGO_PASSWORD: example
    links:
        - db
